name: saasify_lite
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter


  pdf: ^3.6.0
  intl: ^0.17.0
  uuid: ^3.0.4
  crypto: ^3.0.1
  printing: ^5.9.0
  open_file: ^3.3.2
  googleapis: ^11.4.0
  share_plus: ^7.2.1
  google_fonts: ^6.1.0
  path_provider:
  universal_html: ^2.2.4
  draggable_home: ^1.0.5
  flutter_dotenv:
  cupertino_icons: ^1.0.8
  googleapis_auth: ^1.0.0
  supabase_flutter:
  shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  patrol: ^3.14.1
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
