import 'package:intl/intl.dart';
import 'package:saasify_lite/gServices/g_sheet_services.dart';
import 'package:saasify_lite/utils/utils.dart';

class AddItemService {
  static Future<void> addItem({
    required String productName,
    required String description,
    required String price,
  }) async {
    if (!GSheetsService.isInitialized) {
      await GSheetsService.init();
    }

    final now = DateTime.now();
    final dateFormat = DateFormat('dd/MM/yyyy');
    final createdAt = dateFormat.format(now);
    final updatedAt = dateFormat.format(now);

    final values = [
      generateUserId(), // Item ID will be auto-generated by the sheet
      productName,
      description,
      price,
      createdAt,
      updatedAt,
    ];

    await GSheetsService.itemSheet!.values.appendRow(values);
  }
}

class AddItemBloc {
  Future<void> addItem({
    required String productName,
    required String description,
    required String price,
  }) async {
    await AddItemService.addItem(
      productName: productName,
      description: description,
      price: price,
    );
  }
}
